---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: triliovault-demo-platform-{{ .Values.username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: triliovault-demo-platform-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: {{ .Values.username }}
