---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-{{ $.Values.username }}
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .namespace }}
roleRef:
  kind: ClusterRole
  name: datavolume-admin
  apiGroup: rbac.authorization.k8s.io
---
