---
# originalvms-dr-admin5-backupplan-a
apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  name: backupplan-odf-s3-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  backupConfig:
    target:
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
      name: target-odf-s3-{{ .Values.username }}
---
apiVersion: triliovault.trilio.io/v1
kind: Backup
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  name: backup-odf-s3-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  backupPlan:
    kind: BackupPlan
    name: backupplan-odf-s3-{{ .Values.username }}
    namespace: {{ .Values.namespace }}-{{ .Values.username }}
  type: Full
