---
apiVersion: triliovault.trilio.io/v1
kind: BackupPlan
metadata:
  # name: originalvms-dr-admin4-backupplan-352
  name: {{ .Values.username }}-{{ .Values.username }}-backupplan-a
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  backupConfig:
    schedulePolicy: {}
    target:
      apiVersion: triliovault.trilio.io/v1
      kind: Target
      name: target-1-{{ .Values.username }}
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
  backupPlanComponents: {}
  snapshotConfig:
    schedulePolicy: {}
    target:
      apiVersion: triliovault.trilio.io/v1
      kind: Target
      name: target-1-{{ .Values.username }}
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
---
apiVersion: triliovault.trilio.io/v1
kind: Backup
metadata:
  name: backup1-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  backupPlan:
    apiVersion: triliovault.trilio.io/v1
    kind: BackupPlan
    # name: originalvms-dr-admin4-backupplan-352
    name: {{ .Values.username }}-{{ .Values.username }}-backupplan-a
    namespace: {{ .Values.namespace }}-{{ .Values.username }}
  type: Full
