{{- if .Values.backend.odf }}
---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: obc-trilio-bucket-odf
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  generateBucketName: trilio-bucket-odf
  storageClassName: openshift-storage.noobaa.io
{{- end }}
