{{- if eq .Values.backend.minio "true" }}
---
kind: Secret
apiVersion: v1
metadata:
  name: minio-s3-login
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
data:
  accessKey: bWluaW8=
  secretKey: {{ .Values.common_password | b64enc }}
type: Opaque
{{- end }}
{{- if eq .Values.backend.odf "true" }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: odf-secret-job-{{ .Values.username }}
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      backoffLimit: 1
      restartPolicy: Never
      serviceAccountName: odf-secret-job
      containers:
      - name: odf-secret-patch-{{ .Values.username }}
        image: registry.redhat.io/openshift4/ose-cli:latest
        # image: quay.io/agnosticd/ee-multicloud:v0.1.2
        command:
        - /bin/sh
        - -c
        - |
          set -euxo pipefail
          ACCESS_KEY=$(oc get -n default secret trilio-bucket-odf -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)
          SECRET_KEY=$(oc get -n default secret trilio-bucket-odf -o jsonpath='{.data.AWS_SECRET_ACCESS_KEY}' | base64 -d)

          oc create -n {{ .Values.namespace }}-{{ .Values.username }} secret generic trilio-odf-s3 \
          --from-literal=accessKey="${ACCESS_KEY}" \
          --from-literal=secretKey="${SECRET_KEY}" || true
{{- end }}
