---
kind: Secret
apiVersion: v1
metadata:
  name: minio-s3-login
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
data:
  accessKey: bWluaW8=
  secretKey: {{ .Values.common_password | b64enc }}
type: Opaque
