{{- if .Values.backend.minio }}
---
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: minio-target-1-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  nfsCredentials:
    nfsExport: ''
  objectStoreCredentials:
    bucketName: s3-{{ .Values.username }}
    url: 'http://minio.minio.svc.cluster.local:9000/'
    skipCertVerification: true
    credentialSecret:
      apiVersion: v1
      kind: Secret
      name: minio-s3-login
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
  type: ObjectStore
  vendor: MinIO
{{- end }}
{{- if .Values.backend.odf }}
---
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: odf-target-1-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  nfsCredentials:
    nfsExport: ''
  objectStoreCredentials:
    skipCertVerification: true
    bucketName: odf-trilio-b0c08db9-436c-430f-9eeb-8d5334e109b9s3
    url: 'https://s3.openshift-storage.svc:443'
    credentialSecret:
      apiVersion: v1
      kind: Secret
      name: odf-s3-login
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
  type: ObjectStore
  vendor: MinIO
{{- end }}
{{- if .Values.backend.odf }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: odf-target-job-{{ .Values.username }}
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  template:
    spec:
      restartPolicy: Never
      serviceAccountName: odf-secret-job
      containers:
      - name: odf-target-patch-{{ .Values.username }}
        image: registry.redhat.io/openshift4/ose-cli:latest
        command:
        - /bin/sh
        - -c
        - |

          BUCKET_NAME=$(oc get -n default secret trilio-bucket-odf -o jsonpath='{.data.AWS_ACCESS_KEY_ID}' | base64 -d)

          cat << EOF | oc apply -f -
          apiVersion: triliovault.trilio.io/v1
          kind: Target
          metadata:
            name: odf-target-s3-{{ .Values.username }}
            namespace: {{ .Values.namespace }}-{{ .Values.username }}
          spec:
            nfsCredentials:
              nfsExport: ''
            objectStoreCredentials:
              skipCertVerification: true
              bucketName: ${BUCKET_NAME}
              url: 'https://s3.openshift-storage.svc:443'
              credentialSecret:
                apiVersion: v1
                kind: Secret
                name: trilio-odf-s3
                namespace: {{ .Values.namespace }}-{{ .Values.username }}
            type: ObjectStore
            vendor: Other
          EOF

{{- end }}
