apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: target-1-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  nfsCredentials:
    nfsExport: ''
  objectStoreCredentials:
    bucketName: s3-{{ .Values.username }}
    credentialSecret:
      apiVersion: v1
      kind: Secret
      name: minio-s3-login
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
    url: 'http://minio.minio.svc.cluster.local:9000/'
  type: ObjectStore
  vendor: MinIO
