# make a job to do the patch
---
apiVersion: batch/v1
kind: Job
metadata:
  name: noobaa-backing-store-job
  namespace: default
spec:
  template:
    spec:
      backoffLimit: 1
      restartPolicy: Never
      serviceAccountName: odf-secret-job
      containers:
      - name: noobaa-backing-store-patch
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli
        # image: quay.io/agnosticd/ee-multicloud:v0.1.2
        command:
        - /bin/sh
        - -c
        - |
          set -euxo pipefail
          oc patch BackingStore noobaa-default-backing-store -n openshift-storage --type merge  --patch '{"spec":{"pvPool":{"resources":{"limits":{"memory":"1G","cpu":1}}}}}'
{{- end }}
