# job is in helm chart /loadtest/secret.yaml
{{- if .Values.backend.odf }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odf-secret-job
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odf-secret-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: odf-secret-job
  namespace: default
{{- end }}
