# job is in helm chart /loadtest/secret.yaml
{{- if .Values.backend.odf }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: odf-secret-job
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: odf-secret-job
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: odf-secret-job
  namespace: default
---
apiVersion: batch/v1
kind: Job
metadata:
  name: noobaa-backing-store-job
  namespace: default
spec:
  template:
    spec:
      backoffLimit: 1
      restartPolicy: Never
      serviceAccountName: odf-secret-job
      containers:
      - name: noobaa-backing-store-patch
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli
        # image: quay.io/agnosticd/ee-multicloud:v0.1.2
        command:
        - /bin/sh
        - -c
        - |
          set -euxo pipefail
          oc patch BackingStore noobaa-default-backing-store -n openshift-storage --type merge  --patch '{"spec":{"pvPool":{"resources":{"limits":{"memory":"1G","cpu":1}}}}}'
{{- end }}
