apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: clone-sourcer
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datavolume-cloner
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:authenticated
