{{- with .Values.vms }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .namespace }}-{{ $.Values.username }}
{{- if .label }}
  labels:
{{ .label | indent 4 }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-clone-{{ $.Values.username }}
  namespace: default
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ .namespace }}-{{ $.Values.username }}
roleRef:
  kind: ClusterRole
  name: datavolume-cloner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin
  namespace: {{ .namespace }}-{{ $.Values.username }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: admin
{{- $max_vms := ( add ( int .count ) 1 ) }}
{{- range $vm_index := untilStep 1 ( int $max_vms ) 1 }}
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  labels:
    app: winweb01
    app.kubernetes.io/part-of: 3-Tier-App
    vm.kubevirt.io/template.revision: '1'
    vm.kubevirt.io/template.version: v0.25.0
  name: winweb01
  namespace: {{ $.Values.vms.namespace }}-{{ $.Values.username }}
spec:
  dataVolumeTemplates:
  - apiVersion: cdi.kubevirt.io/v1beta1
    kind: DataVolume
    metadata:
      name: winweb01-{{ $vm_index }}
    spec:
      source:
        snapshot:
          name: winweb01-volumesnapshot
          namespace: default
        # pvc:
        #   name: winweb01
        #   namespace: default
        # http:
        #   url: image url/winweb01.qcow2
      storage:
        resources:
          requests:
            storage: 90Gi
  runStrategy: {{ $.Values.vms.runStrategy }}
  template:
    metadata:
      labels:
        env: {{ $.Values.vms.route }}
    spec:
      terminationGracePeriodSeconds: 0
      domain:
        clock:
          timer:
            hpet:
              present: false
            hyperv: {}
            pit:
              tickPolicy: delay
            rtc:
              tickPolicy: catchup
          utc: {}
        cpu:
          cores: 1
          sockets: 2
          threads: 1
        devices:
          disks:
          - disk:
              bus: sata
            name: rootdisk
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - masquerade: {}
            model: e1000e
            name: default
        features:
          acpi: {}
          apic: {}
          hyperv:
            frequencies: {}
            ipi: {}
            relaxed: {}
            reset: {}
            runtime: {}
            spinlocks:
              spinlocks: 8191
            synic: {}
            synictimer:
              direct: {}
            tlbflush: {}
            vapic: {}
            vpindex: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi: {}
        machine:
          type: {{ $.Values.vms.machineType }}
        memory:
          guest: 1Gi
        resources:
          requests:
            memory: 1Gi
      evictionStrategy: {{ $.Values.vms.evictionStrategy }}
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: winweb01-{{ $vm_index }}
        name: rootdisk
{{- end }}
{{- end }}
