{{- if .Values.backend.minio }}
---
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: minio-target-1-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  nfsCredentials:
    nfsExport: ''
  objectStoreCredentials:
    bucketName: s3-{{ .Values.username }}
    url: 'http://minio.minio.svc.cluster.local:9000/'
    skipCertVerification: true
    credentialSecret:
      apiVersion: v1
      kind: Secret
      name: minio-s3-login
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
  type: ObjectStore
  vendor: MinIO
{{- end }}
{{- if .Values.backend.odf }}
---
apiVersion: triliovault.trilio.io/v1
kind: Target
metadata:
  name: odf-target-1-{{ .Values.username }}
  namespace: {{ .Values.namespace }}-{{ .Values.username }}
spec:
  nfsCredentials:
    nfsExport: ''
  objectStoreCredentials:
    skipCertVerification: true
    bucketName: odf-trilio-b0c08db9-436c-430f-9eeb-8d5334e109b9s3
    url: 'https://s3.openshift-storage.svc:443'
    credentialSecret:
      apiVersion: v1
      kind: Secret
      name: odf-s3-login
      namespace: {{ .Values.namespace }}-{{ .Values.username }}
  type: ObjectStore
  vendor: MinIO
{{- end }}
